// Generated by CoffeeScript 1.7.1
requirejs.config({
  paths: {
    'text': '../lib/require/text',
    'durandal': '../lib/durandal/js',
    'plugins': '../lib/durandal/js/plugins',
    'transactions': '../lib/durandal/js/transactions',
    'knockout': '../lib/knockout/knockout-3.1.0',
    'jquery': '../lib/jquery/jquery-1.9.1'
  }
});

define(function(require) {
  var app, system;
  system = require('durandal/system');
  app = require('durandal/app');
  system.debug(true);
  app.title = 'Durandal Starter Kit';
  app.configurePlugins({
    router: true,
    dialog: true
  });
  app.start().then(function() {
    app.setRoot('shell');
    console.log('fuck......');
  });
});
